default:
  debug: true
  digest: false
  compress: false

development:
  debug: true

staging:
  deploy_strategy:local
  deploy_path: compiled/staging

production:
  deploy_strategy:local
  deploy_path: compiled/production
  debug: false
  digest: true
  compress: true